name: Continuous Integration


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:

  test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Test
        run: make test
